apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-back-dep
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: 057494829841.dkr.ecr.eu-west-3.amazonaws.com/3-tier-for-backend-assi
          ports:
          - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: real-estate-back-svc
spec:
  selector:
    app: backend-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
